# Generated by Django 2.2.12 on 2022-05-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
