# Generated by Django 4.0.4 on 2022-07-26 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsDb', '0002_alter_competition_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 14, 11, 32, 641094), null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 14, 11, 32, 641079), null=True, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='points',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 14, 11, 32, 641838), null=True, verbose_name='Data utworzenia'),
        ),
    ]
