# Generated by Django 4.0.4 on 2022-07-27 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsDb', '0003_alter_competition_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 1, 30, 360878), null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 1, 30, 360863), null=True, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='points',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 1, 30, 361588), null=True, verbose_name='Data utworzenia'),
        ),
    ]
